apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: crud-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crud-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    target:
        type: Utilization
        averageUtilization: 50
